openapi: 3.0.3
info:
  title: Intranet Educativo - User Module
  version: 1.0.0

servers:
  - url: http://localhost:8081

tags:
  - name: user
    description: All about user module

paths:
  /user/hi:
    get:
      tags:
        - user
      summary: Test endpoint
      description: Returns a greeting string.
      operationId: testUserModule
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /user:
    post:
      tags:
        - user
      summary: Create a user
      description: Create a new User.
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - user
      summary: Edit a user
      description: Edit an existing user.
      operationId: editUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User modified successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid input
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/all:
    get:
      tags:
        - user
      summary: Get all users
      description: Retrieve a list of all users.
      operationId: getUsersList
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/allById:
    post:
      tags:
        - user
      summary: Get users by IDs
      description: Retrieve a list of users by their IDs.
      operationId: getUsersListById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                format: uuid
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /user/{id}:
    get:
      tags:
        - user
      summary: Get user by ID
      description: Retrieve a user by their ID.
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - user
      summary: Delete user by ID
      description: Delete a user by their ID.
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '404':
          description: User not found
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        father_surname:
          type: string
        mother_surname:
          type: string
        born_date:
          type: string
        phone:
          type: string
        sex:
          type: string
        address:
          type: string
        photo_url:
          type: string
        role:
          type: string
        curp:
          type: string
        status:
          type: string
        registry_date:
          type: string
          format: date-time
        email:
          type: string
        password:
          type: string
        access_card_code:
          type: string

    ApiResponse:
      type: object
      properties:
        message:
          type: string
        data:
          oneOf:
            - $ref: '#/components/schemas/User'
            - type: array
              items:
                $ref: '#/components/schemas/User'
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        error:
          type: string
        status:
          type: integer
