spring:
  application:
    name: user
  cloud:
    config:
      profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/intranetdb?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "root"
management:
  graphite:
    metrics:
      export:
        enabled: false
  security:
    user:
      name: ""
      password: ""

server:
  port: 0

logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
