spring:
  application:
    name: user
  cloud:
    config:
      profile: dev
management:
  graphite:
    metrics:
      export:
        enabled: false
server:
  port: 0

logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
