spring:
  application:
    name: user

management:
  graphite:
    metrics:
      export:
        enabled: false
server:
  port: 0

logging:
  level:
    org.springframework.web: "debug"
    org.hibernate: "error"
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
