version: '3.8'

services:

  discovery:
    build: ./discovery
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - spring-net

  user:
    build: ./user
    container_name: user
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - spring-net

  member:
    build: ./member
    container_name: member
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
