networks:
  spring-net:
    driver: bridge
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intranetdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-net

  registry:
    build: ./registry
    platform: linux/amd64
    container_name: registry-service
    restart: always
    ports:
      - "8761:8761"
    volumes:
      - registry_data:/data
    networks:
      - spring-net

  user:
    build: ./user
    container_name: user
    restart: always
    platform: linux/amd64
    depends_on:
      - registry
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - user_data:/data
    networks:
      - spring-net

  member:
    build: ./member
    container_name: member
    restart: always
    platform: linux/amd64
    depends_on:
      - registry
      - mysql
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - member_data:/data
    networks:
      - spring-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    platform: linux/amd64
    ports:
      - "8080:8080"
    depends_on:
      - member
      - user
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry-service:8761/eureka/
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - api_gateway_data:/data
    networks:
      - spring-net

volumes:
  registry_data:
  api_gateway_data:
  user_data:
  member_data:
  mysql_data:
