server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/user/**
            - id: member
              uri: lb://member
              predicates:
                - Path=/member/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
