spring:
  application:
    name: members
  cloud:
    config:
      profile: dev
management:
  graphite:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
