spring:
  application:
    name: registry
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: registry-service
    prefer-ip-address: true
    
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
