spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NOEL318/Universidad-Humanista
          clone-on-start: true
server:
  port: 8888
